[package]
name = "stegano-cli"
description = "Steganography command line tool. Supports hiding data in PNG images via LSB Encoding."
version = "0.3.1-beta.1"
authors = ["Sven Assmann <sven.assmann.it@gmail.com>"]
edition = "2018"
license-file = "LICENSE"
homepage = "https://www.stegano.org"
readme = "README.md"
keywords = ["steganography", "image", "hiding", "unveil", "commandline"]
categories = ["encoding", "multimedia::encoding", "multimedia::images", "command-line-utilities"]
maintenance = { status = "actively-developed" }
repository = "https://github.com/steganogram/cli.stegano.org"
exclude = [".ci/*", ".gitignore", ".travis.yml"]

[badges]
travis-ci = { repository = "steganogram/cli.stegano.org", branch = "master" }

[dependencies]
# stegano-core = { path = "../stegano-core" }
# stegano-core = { git = "https://github.com/steganogram/cli.stegano.org", branch = "master" }
stegano-core = "0.3.1-beta.1"
clap = "2.33.0"

[[bin]]
name = "stegano"
path = "src/main.rs"