[package]
name = "stegano-cli"
version = "0.1.0"
authors = ["Sven Assmann <sven.assmann.it@gmail.com>"]
edition = "2018"
license-file = "LICENSE"

[dependencies]
stegano-core = { path = "../stegano-core" }
clap = "2.33.0"

[[bin]]
name = "stegano"
path = "src/main.rs"